### ISSUE TITLE
TODO w/ 2.2.2

### ISSUE THREAD

**Issue by Loxoz** [Loxoz/Electryan-Pack#1]
**Electryan Pack 2.2.2 TODO**

FIX

- [ ] disable drawer auto packing when breaking
- [ ] add tiny progression's dragon scales loot to woot

MODS

- [ ] FTB Stuff mods
- [ ] Quests
